### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by hellocatfood** [fpermana/svgbuild-py3#1]
Thanks for rewriting the script in python3! I'm using the script on Ubuntu 20.04 and it appears to start running but gives me a `[Errno 2] No such file or directory:` error after a bit. I ran the following command on the island of creativity file from the inkscape website:

`python3 main.py --build-path --detail-path --path-node-count=2 --use-object-color --zoom=4 inkscape-island-of-creativity.svg`

I did a video recording of it:

![Peek 2020-09-29 21-42](https://user-images.githubusercontent.com/151947/94613594-b3d27500-029c-11eb-857a-f3bd90e5ffa3.gif)

[simplescreenrecorder-2020-09-29_21.36.23.zip](https://github.com/fpermana/svgbuild-py3/files/5301749/simplescreenrecorder-2020-09-29_21.36.23.zip)

I ran the same and different commands on other svg files and they'd all fail with the same error at seemingly arbitrary points.

**Comment by fpermana** [comment]
That is weird.
Generated png should be inside the folder (inkscape-island-of-creativity).
What is your Python and Inkscape version?

**Comment by hellocatfood** [comment]
So I checked and it looks like I'm using a beta version of Inkscape (`inkscape-trunk` from this ppa https://launchpad.net/~inkscape.dev/+archive/ubuntu/trunk )

After downgrading to the stable inkscape from this repository https://launchpad.net/~inkscape.dev/+archive/ubuntu/stable (Inkscape 1.0 isn't in the Ubuntu 20.04 repositories yet) everything was working.

Other than that I'm using Python version 3.8.

**Comment by hellocatfood** [comment]
If future versions of inkscape save images differently this could become a problem but for now everything's working. Thanks for remaking the script!

**Comment by fpermana** [comment]
Well noted, @hellocatfood . I currently use Inkscape only via command line for this svgbuild.
I'm able to use Inkscape version 1.0 via docker on Alpine Linux images, it's still worked correctly.
But I haven't tested on Ubuntu 20.04 with Beta version of Inkscape.
