### ISSUE TITLE
--use-object-line-color not working

### ISSUE THREAD

**Issue by hellocatfood** [fpermana/svgbuild-py3#2]
I've noticed that the `--use-object-line-color` option isn't have an effect when rebuilding an object (using `--build-path`)

Here's the svg that I'm using

[drawing_line_colour.zip](https://github.com/fpermana/svgbuild-py3/files/6411781/drawing_line_colour.zip)

In drawing_line_colour.svg each object has a stroke that is the same as its fill colour.

I ran the following script on the drawing_line_colour.svg

`python3 main.py --use-object-line-color --use-object-color --page-view --build-path --folder yo --name finished drawing.svg`

Which gave this result

https://user-images.githubusercontent.com/151947/116819872-0db85780-ab6a-11eb-8b1d-31e66423a6c2.mp4

As you can when each object is being rebuilt it's using a black outline, even though I've used `--use-object-line-color`. Is this a bug?

Additionally, can it be set to have no line at all i.e. transparent line?

**Comment by fpermana** [comment]
Will take a look at it and fix it. I once added transparent line as far I remember, but I forgot whether it is in this repository or in old one, or probably I just missed it.
Thank you for your feedback.

**Comment by hellocatfood** [comment]
For the time being I've removed the bit of code for rendering line colours, which is lines 591 - 599 in svgbuild.py. Of course this stops lines from being draw but then, in Inkscape, I convert the stroke to a path by going to Path > Stroke to Path. Not idea but works for now

**Comment by fpermana** [comment]
I just made an update. It should be solve this problem. Thank you.

**Comment by hellocatfood** [comment]
This works great, thank you! It would be great if it could use the line style as well. For example, in one of my drawings the line thickness is 5mm but it draws it with a thin line. I'll try and look in the code and add that in myself.

In the meantime thanks for being quick with fixing it! :-)
